config/routes.rb
Rails.application.routes.draw do
  resources :abouts
  resource :homepage, :users do
  end

  resource :admins do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    get '/management', to: 'admins#management'
    post '/send_invitation', to: 'admins#send_invitation'
  end

  resource :artpieces do
    post '/update_homepage_picture', to: 'artpieces#update_homepage_picture'
    post '/move_up', to: 'artpieces#move_up'
    post '/move_down', to: 'artpieces#move_down'
  end

  root to: 'homepages#index'

end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artpiece.rb
class Artpiece < ApplicationRecord
  has_attached_file :image, styles: { large: "600x600", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates :image, attachment_presence: true
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :title, uniqueness: true, presence: true
  validates :type_of_art, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :update, :destroy]

  def index
    @about = About.all.last
  end

  def show
  end

  def edit
    @about = About.all.last
  end

  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to '/admins', notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @about = About.all.last
    @about.update(about_params)
  end


  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def display
    About.all.update_all(displayed: false)
    @about.update_columns(displayed: true)
    redirect_to admins_path
  end

  private

    def set_about
      @about = About.all.last
    end

    def about_params
      params.require(:about).permit(:content)
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  before_action :authorize
  before_action :set_about, only: [:show]
  before_action :set_artTypes, only: [:show]

  def show
    @artpiece = Artpiece.new
  end

  def management
    @users = User.all
  end

  def send_invitation
    name = params[:name]
    email = params[:email]
    UserMailer::invitation_email(name,email).deliver
  end

  private

  def set_about
    @abouts = About.all
    if @abouts.size > 0
      @about = About.all.last
    else
      @about = About.new
    end
  end

  def set_artTypes
    @artTypes = []
    @artTitles = []

    Artpiece.all.each do |artpiece|
      unless @artTitles.include?(artpiece.type_of_art)
        @artTitles << artpiece.type_of_art
      end
      @artTitles.sort!
    end

    @artTitles.each do |artTitle|
      @artTypes << Artpiece.where(type_of_art: artTitle).order(:order)
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/admins/login' unless current_user
  end
end

app/controllers/artpieces_controller.rb
class ArtpiecesController < ApplicationController

  def create
    @artpiece = Artpiece.new(artpiece_params)
    set_order(@artpiece)
    @artpiece.save!
    redirect_to admins_path
  end

  def destroy
    Artpiece.find(params[:id]).destroy
    redirect_to admins_path
  end

  def edit
    @artpiece = Artpiece.find(params[:id])
  end

  def update
    @artpiece = Artpiece.find(params[:artpiece][:id])
    @artpiece.update(artpiece_params)
    redirect_to admins_path
  end

  def move_up
    @artpiece = Artpiece.find(params[:id])
    current_order = @artpiece.order

    if @artpiece.order > 1
      Artpiece.where(type_of_art: @artpiece.type_of_art, order: (current_order - 1)).first.update_columns(order: current_order)
      @artpiece.update_columns(order:(current_order - 1))
    end
    redirect_to admins_path
  end

  def move_down
    @artpiece = Artpiece.find(params[:id])
    current_order = @artpiece.order

    unless Artpiece.where(type_of_art: @artpiece.type_of_art, order: current_order + 1).empty?
      Artpiece.where(type_of_art: @artpiece.type_of_art, order: current_order + 1).first.update_columns(order: current_order)
      @artpiece.update_columns(order: (current_order + 1))
    end
    redirect_to admins_path
  end

  def update_homepage_picture
    Artpiece.all.update_all(homepage_picture: false)
    @artpiece = Artpiece.find(params[:id])
    @artpiece.update_columns(homepage_picture: true)
    redirect_to admins_path
  end

  private

  def artpiece_params
    params.require(:artpiece).permit(:image, :title, :type_of_art, :year)
  end

  def set_order(artpiece)
    if Artpiece.where(type_of_art: artpiece.type_of_art).empty?
      artpiece.order = 1
    else
      artpiece.order = Artpiece.where(type_of_art: artpiece.type_of_art).last.order + 1
    end
  end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :set_artTypes

  def index
    @homepage_picture = Artpiece.where(homepage_picture: true).first
    @drawings = Artpiece.where(type_of_art: 'Drawing')
    @paintings = Artpiece.where(type_of_art: 'Painting')
    @printmakings = Artpiece.where(type_of_art: 'Printmaking')
  end

  private

  def set_artTypes
    @artTypes = []
    @artTitles = []

    Artpiece.all.each do |artpiece|
      unless @artTitles.include?(artpiece.type_of_art)
        @artTitles << artpiece.type_of_art
      end
      @artTitles.sort!
    end

    @artTitles.each do |artTitle|
      @artTypes << Artpiece.where(type_of_art: artTitle).order(:order)
    end

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.where(username: params[:username]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admins_path
    else
      redirect_to login_admins_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def add_user
  end

  def send_invitation
    name = params[:name]
    email = params[:email]
    UserMailer::invitation_email(name,email).deliver
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/admins'
    else
      redirect_to '/users/new'
    end
  end

  def delete
    user = User.where(username: params[:username])
    user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artpieces_helper.rb
module ArtpiecesHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/_form.html.erb
<%= form_for(about) do |f| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <%= form_for @about, url: { action: 'update'} do |form| %>
      <h3>Edit About File</h3>
      <div class='form-group'>
        <%= form.label :content %>
        <%= form.text_area :content %>
      </div>
      <%= form.button :submit, value:'Update About file', class: 'btn btn-default' %>
    <% end %>
  </body>
</html>

app/views/abouts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style media="screen">

      .artistname {
        font-size: 20px;
        font-weight: bold;
        color: black;
        background:none;
        border:none;
        padding:0;
        cursor: pointer;
        font-size: 10px;
      }

      .container {
        padding-top: 10px;
      }

      .jumbotron {
        background-color: white;
      }

      .glyphicon {
          font-size: 30px;
      }

    </style>
    <title></title>
  </head>
  <body>
    <div class='container'>
      <a href='/' class='artistname'><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a>
      <% if About.all.size > 0%>
        <div class='jumbotron'>
          <%= simple_format(@about.content)%>
        </div>
      <% end %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/abouts/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <style media="screen">

    </style>
  </head>
  <body>
    <% if @about != nil %>
      <div class='container'>
        <div class="jumbotron">
            <%= simple_format(@about.content)%>
        </div>
      </div>
      <%= link_to 'Edit', edit_abouts_path %>
    <% end %>
    <%= link_to 'Back', admins_path %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/admins/management.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <table id='usersList'>
      <tr>
        <td>Username</td>
        <td>Last connection</td>
        <td>delete</td>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td>last connection</td>
          <td><%= link_to 'x', users_path(id: user.id), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: 'button'%></td>
        </tr>
      <% end %>
    </table>

    <div class='user_form'>
      <%= form_for :email, url: '/users/send_invitation' do |form| %>
      <%= form.label :name %>
      <%= form.text_field :name %>
      <%= form.label :email %>
      <%= form.text_field :email %>
      <%= form.submit 'Send invitation' %>
      <% end %>
    </div>

  </body>
</html>

app/views/admins/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style media="screen">
      .form-inline {
        border: 1px solid grey;
        border-radius: 5px;
        background-color: #d9d9db;
      }
      .col-lg-3, .col-md-4, .col-xs-6 {
        border: 2px solid grey;
        border-radius: 5px;
      }

      .artName {
        text-align: center;
        font-weight: bold;
      }

      .about_file {
        padding-bottom: 10px;
      }
    </style>
    <title>Admin Page</title>
  </head>
  <body>
    <div class="container">
      <%= link_to 'Admin management', management_admins_path, class: 'btn btn-info' %>
      <%= link_to 'Add a new admin', new_users_path, class: 'btn btn-info' %><br>

      <datalist id='types'>
        <% @artTitles.each do |artTitle| %>
          <option  value= "<%= artTitle %>" >
        <% end %>
      </datalist><br>

        <%= form_for @artpiece do |form| %>
          <h3>Add Picture</h3>
          <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, required: 'true' %><br>
          </div>
          <div class="form-group">
            <%= form.label :type_of_art %>
            <%= form.text_field :type_of_art, list: 'types', required: 'true' %><br>
          </div>
          <div class="form-group">
            <%= form.label :image %>
            <%= form.file_field :image, class: 'upload' %>
          </div>
          <div class="form-group">
            <%= form.label :year %>
            <%= form.select :year, (Time.zone.now.year - 100)..(Time.zone.now.year + 1), selected: Time.zone.now.year %>
          </div>
          <%= form.button :submit, value: 'Upload Art Piece', class:"btn btn-default" %>
        <% end %><br>


      <div class="row">
        <% @artTypes.each do |artType| %>

          <div class="col-lg-4 col-md-4 col-s-4 col-xs-4">
            <div class='artName'>
              <% number_of_artpieces = artType.size %>
              <% if number_of_artpieces > 0 %>
                <%= artType.first.type_of_art %>
              <% end %>
            </div>


            <% artType.each do |artpiece| %>
              <div class='art'>
                <%= artpiece.title %><br>
                <%= image_tag artpiece.image.url(:thumb), class: 'image' %>
                <%= link_to 'update', edit_artpieces_path(id: artpiece.id), class: 'button' %>
                <%= link_to 'delete', artpieces_path(id: artpiece.id), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: 'button' %><br>
                <%= form_tag(move_up_artpieces_path, method: 'post') do %>
                  <%= hidden_field_tag :id, artpiece.id %>
                  <%= button_tag '', id: "chevron up #{artpiece.title}", class:'glyphicon glyphicon-chevron-up', aria: {hidden: true} %>
                <% end %>
                <%= form_tag(move_down_artpieces_path, method: 'post') do %>
                  <%= hidden_field_tag :id, artpiece.id %>
                  <%= button_tag '', id: "chevron down #{artpiece.title}", class:'glyphicon glyphicon-chevron-down', aria: {hidden: true} %>
                <% end %>
              </div>
              <%= form_tag(update_homepage_picture_artpieces_path, method: 'post') do %>
                <%= hidden_field_tag :id, artpiece.id %>
                <%= button_tag 'make homepage pic', id:'homepage picture', class:'btn btn-primary btn-sm' %>
              <% end %>
            <% end %>
          </div>

        <% end %>
      </div>

      <div class='about_file'>
        <% if @abouts.size > 0 %>
        <a href="/abouts/<%= @about.id %>/edit">Update About file</a>
        <% else %>
        <%= form_for @about do |form| %>
        <h3>Create About File</h3>
        <div class='form-group'>
          <%= form.label :content %>
          <%= form.text_area :content %>
        </div>
        <%= form.button :submit, value:'Create About file', class: 'btn btn-default' %>
        <% end %>
        <% end %>
      </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/artpieces/drawings.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Drawings</title>

    <style media="screen">
      .carousel-inner {
        background-color: white;
      }

      .carousel-inner > .item > img,
      .carousel-inner > .item > a > img{
      width: 50%;
      max-height: inherit;
      margin: auto;

      }

      .drawing_title {
        margin: auto;
        width: 50%;
        text-align: center;
      }

    </style>
  </head>

  <body>

    <div class="col-lg-4 col-md-4 col-s-12 col-xs-12">
      <% @drawings.each do |drawing| %>
        <div class="item <%= 'active' if drawing == @drawings[0] %>">
          <%= image_tag drawing.image.url(:large), class: 'img-responsive' %>
          <p class="drawing_title"><%= drawing.title %></p>
        </div>
      <% end %>
    </div>

    <!-- <div id="drawingsCarousel" class="carousel slide" data-wrap="false" >

      <div class="carousel-inner" role="listbox">
        <% @drawings.each do |drawing| %>
          <div class="item <%= 'active' if drawing == @drawings[0] %>">
            <%= image_tag drawing.image.url(:medium), class: 'img-responsive' %>
            <p class="drawing_title"><%= drawing.title %></p>
          </div>
        <% end %>
      </div>

      <a class="left carousel-control" href="#drawingsCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#drawingsCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div> -->


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/artpieces/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style media="screen">
      .form-inline {
        border: 1px solid grey;
        border-radius: 5px;
        background-color: #d9d9db;
      }
      .col-lg-3, .col-md-4, .col-xs-6 {
        border: 1px solid black;
      }

      .artName {
        text-align: center;
        font-weight: bold;
      }
    </style>
    <title> <%= @artpiece.title %></title>
  </head>
  <body>

    <datalist id='types'>
      <option  value='Drawing'>
      <option  value='Painting'>
      <option  value='Printmaking'>
    </datalist><br>

    <%= form_for @artpiece, url: { action: 'update'} do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, required: 'true', value: @artpiece.title %><br>
      </div>
      <div class="form-group">
        <%= form.label :type_of_art %>
        <%= form.text_field :type_of_art, list: 'types', required: 'true', value: @artpiece.type_of_art %><br>
      </div>
      <div class="form-group">
        <%= form.label :year %>
        <%= form.select :year, (Time.zone.now.year - 100)..(Time.zone.now.year + 1), selected: @artpiece.year %>
      </div>
      <%= form.hidden_field :id, value: @artpiece.id %>
      <%= form.button :submit, value: 'Update', class:"btn btn-default" %>
    <% end %><br>
§
    <%= image_tag @artpiece.image.url(:medium), class: 'image' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

  </body>
</html>

app/views/artpieces/paintings.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Paintings</title>

    <style media="screen">
      .carousel-inner {
        background-color: grey;
      }

      .carousel-inner > .item > img,
      .carousel-inner > .item > a > img{
      width: 50%;
      max-height: inherit;
      margin: auto;
      }

      .painting_title {
        margin: auto;
        width: 50%;
        text-align: center;
      }

    </style>
  </head>

  <body>

    <div id="paintingsCarousel" class="carousel slide" data-wrap="false" >

      <div class="carousel-inner" role="listbox">
        <% @paintings.each do |painting| %>
          <div class="item <%= 'active' if painting == @paintings[0] %>">
            <%= image_tag painting.image.url, class: 'img-responsive' %>
            <p class="painting_title"><%= painting.title %></p>

          </div>
        <% end %>
      </div>

      <a class="left carousel-control" href="#paintingsCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#paintingsCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/artpieces/printmakings.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Printmakings</title>

    <style media="screen">
      .carousel-inner {
        background-color: grey;
      }

      .carousel-inner > .item > img,
      .carousel-inner > .item > a > img{
      width: 50%;
      max-height: inherit;
      margin: auto;
      }

      .printmaking_title {
        margin: auto;
        width: 50%;
        text-align: center;
      }

    </style>
  </head>

  <body>

    <div id="printmakingsCarousel" class="carousel slide" data-wrap="false" >

      <div class="carousel-inner" role="listbox">
        <% @printmakings.each do |printmaking| %>
          <div class="item <%= 'active' if printmaking == @printmakings[0] %>">
            <%= image_tag printmaking.image.url, class: 'img-responsive' %>
            <p class="printmaking_title"><%= printmaking.title %></p>

          </div>
        <% end %>
      </div>

      <a class="left carousel-control" href="#printmakingsCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#printmakingsCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Beau Rouse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class='container'>
    <% if current_user %>
      <div class='admin_information'>
        <p class='admin_name'>Signed in as <%= current_user.username %> </p>  <%= link_to 'Logout', logout_admins_path, class: 'button' %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/add_user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class='user_form'>
      <%= form_for :user, url: '/users/send_invitation' do |form| %>
      <%= form.label :name %>
      <%= form.text_field :name %>
      <%= form.label :email %>
      <%= form.text_field :email %>
      <%= form.submit 'Submit' %>
      <% end %>
    </div>

  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <div class='user_form'>
      <%= form_for :user, url: '/users' do |form| %>
      <%= form.label :username %>
      <%= form.text_field :username %>
      <%= form.label :password %>
      <%= form.password_field :password %>
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
      <%= form.submit 'Submit' %>
      <% end %>
    </div>

  </body>
</html>